### ISSUE TITLE
大神请问  关闭dialog没效果 dismies 和 cancel 都没效果

### ISSUE THREAD

**Issue by Dhy521** [zyao89/ZLoading#14]
<img width="934" alt="image" src="https://user-images.githubusercontent.com/23187670/48542736-e5d1cc80-e8fa-11e8-905c-aa7734191c34.png">
请问我是设置错了吗 还是哪里哟问题阿

**Comment by Dhy521** [comment]
我在加载数据的时候走的true  在加载成功走的false

**Comment by htsunshine** [comment]
肯定错了啊，从新new了一个是新的dialog，又不是前面的那个了

**Comment by Dhy521** [comment]
额 我这是初始化的时候 上面只newl了一个阿  if里面两个不都是共用上面new的内一个么

**Comment by Dhy521** [comment]
请问大神 要怎么改阿

**Comment by htsunshine** [comment]
不知道你怎么写的，你把这个dialog弄成全局试试

**Comment by Dhy521** [comment]
我在activity里面没有初始化   我就用的dialog 模式   我上面也只是new了一次  其他地方也没用到  那你是怎么用的啊

**Comment by htsunshine** [comment]
我也是用的dialog模式，没有问题啊，你截图的这个方法不是加载的时候进来一次，结束的时候加载一次，不是两次吗，不是new了两个吗，怎么就是不理解了，难道我理解错了

**Comment by zyao89** [comment]
你每次调用此方法都会 new 一个新对象. 这是错的

**Comment by Dhy521** [comment]
那怎么可以共用一个对象呢？    如果不new的话 可以获取dalog模式弹出么

**Comment by Dhy521** [comment]
就上述代码  如果取消的话  要怎么写呢

**Comment by zyao89** [comment]
> 就上述代码 如果取消的话 要怎么写呢

```java
private ZLoadingDialog mZ = null;
public static void a () {
    if (mZ == null) {
        mZ = new ZLoadingDialog();
    }
    ....
}
```
