### ISSUE TITLE
setCancelable(false) 没效果

### ISSUE THREAD

**Issue by FlyBiao** [zyao89/ZLoading#4]
请问设置了setCancelable(false) 为什么启动加载框的时候 触碰还是会消失了呢？
ZLoadingDialog dialog = new ZLoadingDialog(CashierMainActivity.this);
//        dialog.setLoadingBuilder(Z_TYPE.SNAKE_CIRCLE)//设置类型
//                .setLoadingColor(Color.BLACK)//颜色
//                .setHintText("正在支付中...")
//                .setHintTextSize(16) // 设置字体大小 dp
//                .setHintTextColor(Color.GRAY)// 设置字体颜色
//                .setCancelable(false)
//                .show();

**Comment by zyao89** [comment]
触碰消失应该要设置 setCanceledOnTouchOutside(false);
